apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: xmikova/wac-fe
  newName: xmikova/wac-fe
  newTag: 1.2.0  #aktuálna verzia docker obrazu, ktorú chcete aby používatelia - cvičiaci - videli nasadenú
- name: xmikova/wac-be
  newName: xmikova/wac-be
  newTag: 1.1.0
