apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: pmdl-pharmacy-ufe-link
spec:
  microFrontend: polyfea-md-shell
  element: polyfea-md-app
  attributes:
    - name: headline
      value: Správa liekov a skladu
    - name: short-headline
      value: Správa liekov
    - name: supporting-text
      value: |
        Systém pre správu liekov a nemocničného skladu
    - name: material-icon
      value: medication
    - name: href
      value: ./pmdl-pharmacy
  priority: 10
  displayRules:
    - anyOf:
      - context-name: applications
      - context-name: rail-content
      - context-name: drawer-content
