apiVersion: wac-fiit.github.io/v1alpha1
kind: Project
metadata:
  name: pmdl-pharmacy
spec:
  title: Správa liekov a skladu - Petra Miková, Dominika Lukašáková
  description: Systém pre správu liekov a nemocničného skladu
  authors: "Petra Miková, Dominika Lukašáková"
  frontendRepoUrl: "https://github.com/xmikova/wac-fe"
  backendRepoUrl: "https://github.com/xmikova/wac-be"
  gitopsRepoUrl: "https://github.com/xmikova/wac-gitops"
