apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: xmikova/wac-be
  newName: xmikova/wac-be # {"$imagepolicy":  "wac-hospital:pharmacy-webapi:name"}
  newTag: main.20260421.2046 # {"$imagepolicy": "wac-hospital:pharmacy-webapi:tag"}
- name: xmikova/wac-fe
  newName: xmikova/wac-fe # {"$imagepolicy":  "wac-hospital:pharmacy-ufe:name"}
  newTag: main.20260421.2048 # {"$imagepolicy": "wac-hospital:pharmacy-ufe:tag"}
