apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital
labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital

resources:
- ../../../apps/pmdl-pharmacy-ufe
- ../../../apps/pmdl-pharmacy-webapi
- ../../../apps/mongo-express

patches:
  - path: patches/pharmacy-webapi.service.yaml
  - path: patches/mongodb-auth.secret.yaml

components:
- ../../../components/version-developers
- https://github.com/xmikova/wac-be//deployments/kustomize/components/mongodb
